{% extends "base.phtml" %}

{% block title %}Plundering Rocks{%endblock%}
{% block extrahead %}
<script src="/js/index.js"></script>
<script src="/js/ores.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js"></script>
{%endblock%}
{% block content %}
<div class="pure-g">
<div class="pure-u-1">
<div class="content-box">
<p>Plundering rocks is a (currently) experimental website, to allow miners to anonymously compare their mining against other miners.</p>

<p>No location data will be displayed, and character/corp/alliance names will only be displayed if their owner wishes them to be</p>

<p>Under development, so please excuse the mess</p>
</div>
</div>
<div class="pure-u-1 pure-u-lg-1-2">
<h2>Best Miners This Month</h2>
<ul id="bestOwner">
</ul>
</div>
<div class="pure-u-1  pure-u-lg-1-2">
<h2>Quantity Mined This Month</h2>
<canvas id="totalMined"></canvas>
</div>
</div>
{% endblock %}
