{% extends "base.phtml" %}

{% block title %}Plundering Rocks{%endblock%}

{% block extrahead %}
<script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js"></script>
<script src="/js/owner.js"></script>
<script src="/js/ores.js"></script>
{%endblock%}
{% block content %}
<div class="pure-g">
<div class="pure-u-1" id="owner-add-minion">
<div class="content-box">
<button id="button-add-minion">Add Miner</button>
<ul id="minion-list">
</ul>
</div>
</div>
 <div class="pure-u-1">
<div class="content-box">
<p>This owner has <span id="minerCount"></span> Miners being monitored.</p>
</div>
</div>
<div class="pure-u-1 pure-u-lg-1-2">
<h2>Ore Quantity</h2>
<canvas id="types"></canvas>
</div>
<div class="pure-u-1 pure-u-lg-1-2">
<h2>Ore Value</h2>
<canvas id="values"></canvas>
</div>
</div>
</div>

</div>
{% endblock %}
